server:
  port: 8080

build.name: @project.name@
build.version: @project.version@

spring:
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  feign:
    client:
      config:
        feignName:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: full

app:
  name: ABC Tech API
  api:
    title: ABC Tech API
    version: 1.0.0
    description: API DOC to work ABC Tech
    base-package: br.com.fiap.abctechapi
    contact-name: Grupo B
    swagger:
      enable: true

#logging:
#  level:
#    org:
#      hibernate:
#        type: info
